### PR TITLE
issue #2 - ability to login manually

### PR DESCRIPTION
**Pull request by awis0330**

### CODE REVIEW

**Comment by jterps08** [comment]
This is good stuff @awis0330 ... I will review promptly and connect with you either here or on Slack. Please continue to proceed with any remaining Sprint 0 issues.

**Comment by igaponov** [comment]
Why is there a mix of different js standards in many files?

**Comment by awis0330** [comment]
@igaponov I didn't get your question exactly.
What js standards are you talking?
By the way, I followed the most recent standards of react native.

**Comment by igaponov** [comment]
@awis0330 
require module.exports var - ES5
import export let const class - ES6

**Comment by awis0330** [comment]
@igaponov I see your point. It could lead confusion. Will fix them.

**Comment by jterps08** [comment]
will mark as complete when I've viewed in builds and when we are in alignment on JS standards

**Pull request merged**
